version: '3'
services:
  # account-registration:
  #   container_name: account-registration
  #   build:
  #     context: .
  #     dockerfile: ./account-registration/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./account-registration/contents:/var/task
  #   ports:
  #     - 9000:8080

  # contract-registration:
  #   container_name: contract-registration
  #   build:
  #     context: .
  #     dockerfile: ./contract-registration/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./contract-registration/contents:/var/task
  #   ports:
  #     - 9001:8080

  device-detail:
    container_name: device-detail
    build:
      context: .
      dockerfile: ./device-detail/Dockerfile
    env_file:
      - .env
    volumes:
      - ./device-detail/contents:/var/task
    ports:
      - 9002:8080

  device-history:
    container_name: device-history
    build:
      context: .
      dockerfile: ./device-history/Dockerfile
    env_file:
      - .env
    volumes:
      - ./device-history/contents:/var/task
    ports:
      - 9003:8080

  device-list:
    container_name: device-list
    build:
      context: .
      dockerfile: ./device-list/Dockerfile
    env_file:
      - .env
    volumes:
      - ./device-list/contents:/var/task
    ports:
      - 9004:8080

  device-order:
    container_name: device-order
    build:
      context: .
      dockerfile: ./device-order/Dockerfile
    env_file:
      - .env
    volumes:
      - ./device-order/contents:/var/task
    ports:
      - 9005:8080

  # device-registration:
  #   container_name: device-registration
  #   build:
  #     context: .
  #     dockerfile: ./device-registration/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./device-registration/contents:/var/task
  #   ports:
  #     - 9006:8080

  device-settings:
    container_name: device-settings
    build:
      context: .
      dockerfile: ./device-settings/Dockerfile
    env_file:
      - .env
    volumes:
      - ./device-settings/contents:/var/task
    ports:
      - 9007:8080

  # event-detection:
  #   container_name: event-detection
  #   build:
  #     context: .
  #     dockerfile: ./event-detection/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./event-detection/contents:/var/task
  #   ports:
  #     - 9008:8080

  group-delete:
    container_name: group-delete
    build:
      context: .
      dockerfile: ./group-delete/Dockerfile
    env_file:
      - .env
    volumes:
      - ./group-delete/contents:/var/task
    ports:
      - 9009:8080

  group-detail:
    container_name: group-detail
    build:
      context: .
      dockerfile: ./group-detail/Dockerfile
    env_file:
      - .env
    volumes:
      - ./group-detail/contents:/var/task
    ports:
      - 9010:8080

  group-list:
    container_name: group-list
    build:
      context: .
      dockerfile: ./group-list/Dockerfile
    env_file:
      - .env
    volumes:
      - ./group-list/contents:/var/task
    ports:
      - 9011:8080

  group-settings:
    container_name: group-settings
    build:
      context: .
      dockerfile: ./group-settings/Dockerfile
    env_file:
      - .env
    volumes:
      - ./group-settings/contents:/var/task
    ports:
      - 9012:8080

  # initialreceive-2:
  #   container_name: initialreceive-2
  #   build:
  #     context: .
  #     dockerfile: ./initialreceive-2/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./initialreceive-2/contents:/var/task
  #   ports:
  #     - 9013:8080

  # lockout-check:
  #   container_name: lockout-check
  #   build:
  #     context: .
  #     dockerfile: ./lockout-check/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./lockout-check/contents:/var/task
  #   ports:
  #     - 9014:8080

  # notification-target-delete:
  #   container_name: notification-target-delete
  #   build:
  #     context: .
  #     dockerfile: ./notification-target-delete/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./notification-target-delete/contents:/var/task
  #   ports:
  #     - 9015:8080

  # notification-target-list:
  #   container_name: notification-target-list
  #   build:
  #     context: .
  #     dockerfile: ./notification-target-list/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./notification-target-list/contents:/var/task
  #   ports:
  #     - 9016:8080

  # notification-target-mail-auth:
  #   container_name: notification-target-mail-auth
  #   build:
  #     context: .
  #     dockerfile: ./notification-target-mail-auth/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./notification-target-mail-auth/contents:/var/task
  #   ports:
  #     - 9017:8080

  # notification-target-send-auth-mail:
  #   container_name: notification-target-send-auth-mail
  #   build:
  #     context: .
  #     dockerfile: ./notification-target-send-auth-mail/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./notification-target-send-auth-mail/contents:/var/task
  #   ports:
  #     - 9018:8080

  # notification-target-send-test-mail:
  #   container_name: notification-target-send-test-mail
  #   build:
  #     context: .
  #     dockerfile: ./notification-target-send-test-mail/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./notification-target-send-test-mail/contents:/var/task
  #   ports:
  #     - 9019:8080

  # notification-target-update:
  #   container_name: notification-target-update
  #   build:
  #     context: .
  #     dockerfile: ./notification-target-update/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./notification-target-update/contents:/var/task
  #   ports:
  #     - 9020:8080

  # password-expiration-date:
  #   container_name: notification-target-update
  #   build:
  #     context: .
  #     dockerfile: ./notification-target-update/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./notification-target-update/contents:/var/task
  #   ports:
  #     - 9021:8080

  password-initialsettings:
    container_name: password-initialsettings
    build:
      context: .
      dockerfile: ./password-initialsettings/Dockerfile
    env_file:
      - .env
    volumes:
      - ./password-initialsettings/contents:/var/task
    ports:
      - 9022:8080

  password-reset:
    container_name: password-reset
    build:
      context: .
      dockerfile: ./password-reset/Dockerfile
    env_file:
      - .env
    volumes:
      - ./password-reset/contents:/var/task
    ports:
      - 9023:8080

  password-settings:
    container_name: password-settings
    build:
      context: .
      dockerfile: ./password-settings/Dockerfile
    env_file:
      - .env
    volumes:
      - ./password-settings/contents:/var/task
    ports:
      - 9024:8080

  # receivedata-2:
  #   container_name: receivedata-2
  #   build:
  #     context: .
  #     dockerfile: ./receivedata-2/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./receivedata-2/contents:/var/task
  #   ports:
  #     - 9025:8080

  remote-control:
    container_name: remote-control
    build:
      context: .
      dockerfile: ./remote-control/Dockerfile
    env_file:
      - .env
    volumes:
      - ./remote-control/contents:/var/task
    ports:
      - 9026:8080

  remote-control-list:
    container_name: remote-control-list
    build:
      context: .
      dockerfile: ./remote-control-list/Dockerfile
    env_file:
      - .env
    volumes:
      - ./remote-control-list/contents:/var/task
    ports:
      - 9027:8080

  remote-control-response:
    container_name: remote-control-response
    build:
      context: .
      dockerfile: ./remote-control-response/Dockerfile
    env_file:
      - .env
    volumes:
      - ./remote-control-response/contents:/var/task
    ports:
      - 9028:8080

  remote-control-state-change:
    container_name: remote-control-state-change
    build:
      context: .
      dockerfile: ./remote-control-state-change/Dockerfile
    env_file:
      - .env
    volumes:
      - ./remote-control-state-change/contents:/var/task
    ports:
      - 9029:8080

  remote-control-timeout:
    container_name: remote-control-timeout
    build:
      context: .
      dockerfile: ./remote-control-timeout/Dockerfile
    env_file:
      - .env
    volumes:
      - ./remote-control-timeout/contents:/var/task
    ports:
      - 9030:8080

  timer-control:
    container_name: timer-control
    build:
      context: .
      dockerfile: ./timer-control/Dockerfile
    env_file:
      - .env
    volumes:
      - ./timer-control/contents:/var/task
    ports:
      - 9031:8080

  # user-delete:
  #   container_name: user-delete
  #   build:
  #     context: .
  #     dockerfile: ./user-delete/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./user-delete/contents:/var/task
  #   ports:
  #     - 9032:8080

  user-detail:
    container_name: user-detail
    build:
      context: .
      dockerfile: ./user-detail/Dockerfile
    env_file:
      - .env
    volumes:
      - ./user-detail/contents:/var/task
    ports:
      - 9033:8080

  user-list:
    container_name: user-list
    build:
      context: .
      dockerfile: ./user-list/Dockerfile
    env_file:
      - .env
    volumes:
      - ./user-list/contents:/var/task
    ports:
      - 9034:8080

  # user-notice:
  #   container_name: user-notice
  #   build:
  #     context: .
  #     dockerfile: ./user-notice/Dockerfile
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./user-notice/contents:/var/task
  #   ports:
  #     - 9035:8080

  user-update:
    container_name: user-update
    build:
      context: .
      dockerfile: ./user-update/Dockerfile
    env_file:
      - .env
    volumes:
      - ./user-update/contents:/var/task
    ports:
      - 9036:8080

  device-replacement-list:
    container_name: device-replacement-list
    build:
      context: .
      dockerfile: ./device-replacement-list/Dockerfile
    env_file:
      - .env
    volumes:
      - ./device-replacement-list/contents:/var/task
    ports:
      - 9037:8080

  device-new-registration:
    container_name: device-new-registration
    build:
      context: .
      dockerfile: ./device-new-registration/Dockerfile
    env_file:
      - .env
    volumes:
      - ./device-new-registration/contents:/var/task
    ports:
      - 9038:8080

  localstack:
    image: localstack/localstack:latest
    ports:
      - 4510-4559:4510-4559
      - 4566:4566
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./_local-dev-files/docker/docker.sock:/var/run/docker.sock
      - ./_local-dev-files/localstack/ready.d:/etc/localstack/init/ready.d
      - ./_local-dev-files/localstack/terraform:/usr/local/terraform

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    ports:
      - 8081:8001
    environment:
      - DYNAMO_ENDPOINT=localstack:4566
      - AWS_REGION=ap-northeast-1
    depends_on:
      - localstack
